services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    environment:
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_DATABASE=rinha'
      - 'TZ=America/Sao_Paulo'
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "370MB"
    volumes:
      - ./sql/mysql-init-script.sql:/docker-entrypoint-initdb.d/mysql-init-script.sql
      - ./mysql.conf:/etc/mysql/conf.d/config-file.cnf
    networks:
      - default
    healthcheck:
      test: [ "CMD-SHELL", "mysql -h localhost -uroot -proot" ]
      interval: 5s
      timeout: 5s
      retries: 10
#    ports:
#      - 3306:3306

  app1:
    container_name: app1
    image: quarkus/rinha-backend-2024
    environment:
      - 'QUARKUS_LOG_LEVEL=WARN'
      - 'QUARKUS_DATASOURCE_JDBC_INITIAL_SIZE=5'
      - 'QUARKUS_DATASOURCE_JDBC_MIN_SIZE=5'
      - 'QUARKUS_DATASOURCE_JDBC_MAX_SIZE=5'
      - 'QUARKUS_DATASOURCE_JDBC_DETECT_STATEMENT_LEAKS=false'
      - 'QUARKUS_DATASOURCE_JDBC_ACQUISITION_TIMEOUT=10S'
      - 'QUARKUS_DATASOURCE_JDBC_URL=jdbc:mysql://mysql:3306/rinha?useServerPrepStmts=true&prepStmtCacheSize=500&prepStmtCacheSqlLimit=1024'
      - 'QUARKUS_DATASOURCE_USERNAME=root'
      - 'QUARKUS_DATASOURCE_PASSWORD=root'
      - 'TZ=America/Sao_Paulo'
      - 'JAVA_TOOL_OPTIONS=-XX:ActiveProcessorCount=2'
      - 'QUARKUS_HTTP_PORT=8080'
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "50MB"
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - default

  app2:
    container_name: app2
    image: quarkus/rinha-backend-2024
    environment:
      - 'QUARKUS_LOG_LEVEL=WARN'
      - 'QUARKUS_DATASOURCE_JDBC_INITIAL_SIZE=5'
      - 'QUARKUS_DATASOURCE_JDBC_MIN_SIZE=5'
      - 'QUARKUS_DATASOURCE_JDBC_MAX_SIZE=5'
      - 'QUARKUS_DATASOURCE_JDBC_DETECT_STATEMENT_LEAKS=false'
      - 'QUARKUS_DATASOURCE_JDBC_ACQUISITION_TIMEOUT=10S'
      - 'QUARKUS_DATASOURCE_JDBC_URL=jdbc:mysql://mysql:3306/rinha?useServerPrepStmts=true&prepStmtCacheSize=500&prepStmtCacheSqlLimit=1024'
      - 'QUARKUS_DATASOURCE_USERNAME=root'
      - 'QUARKUS_DATASOURCE_PASSWORD=root'
      - 'TZ=America/Sao_Paulo'
      - 'JAVA_TOOL_OPTIONS=-XX:ActiveProcessorCount=2'
      - 'QUARKUS_HTTP_PORT=8081'
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "50MB"
    ports:
      - 8081:8081
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - default

#  nginx:
#    container_name: nginx
#    image: nginx:latest
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#    ports:
#      - 9999:9999
#    depends_on:
#      - app1
#      - app2
#    deploy:
#      resources:
#        limits:
#          cpus: "0.3"
#          memory: "100MB"
#    networks:
#      - default

  envoy:
    image: envoyproxy/envoy-alpine:v1.21-latest
    container_name: envoy
    environment:
      - 'TZ=America/Sao_Paulo'
    volumes:
      -  ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "9999:9999"
    networks:
      - default
    depends_on:
      - app1
      - app2
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "80MB"

networks:
  default:
    driver: bridge