services:
  database:
    image: mariadb:latest
    container_name: database
    security_opt:
      - seccomp:unconfined
    environment:
      - 'MARIADB_ROOT_PASSWORD=root'
      - 'MARIADB_DATABASE=rinha'
      - 'TZ=America/Sao_Paulo'
      - 'MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true'
      - 'MARIADB_MYSQL_LOCALHOST_USER: 1'
      - 'MARIADB_MYSQL_LOCALHOST_GRANTS: USAGE'
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "280MB"
    volumes:
      - ./sql/mysql-init-script.sql:/docker-entrypoint-initdb.d/mysql-init-script.sql
      - ./mysql.conf:/etc/mysql/conf.d/config-file.cnf
    networks:
      - default
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      interval: 5s
      timeout: 5s
      retries: 10
    ulimits:
      nofile:
        soft: 196608
        hard: 196608

  app1:
    container_name: app1
    image: quarkus/rinha-backend-2024
    environment:
      - 'QUARKUS_LOG_LEVEL=WARN'
      - 'QUARKUS_DATASOURCE_JDBC_INITIAL_SIZE=7'
      - 'QUARKUS_DATASOURCE_JDBC_MIN_SIZE=7'
      - 'QUARKUS_DATASOURCE_JDBC_MAX_SIZE=7'
      - 'QUARKUS_DATASOURCE_JDBC_DETECT_STATEMENT_LEAKS=false'
      - 'QUARKUS_DATASOURCE_JDBC_ACQUISITION_TIMEOUT=10S'
      - 'QUARKUS_DATASOURCE_JDBC_URL=jdbc:mariadb://database:3306/rinha'
      - 'QUARKUS_DATASOURCE_USERNAME=root'
      - 'QUARKUS_DATASOURCE_PASSWORD=root'
      - 'TZ=America/Sao_Paulo'
      - 'QUARKUS_HTTP_PORT=8080'
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "90MB"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - default
    ulimits:
      nofile:
        soft: 98304
        hard: 98304

  app2:
    container_name: app2
    image: quarkus/rinha-backend-2024
    environment:
      - 'QUARKUS_LOG_LEVEL=WARN'
      - 'QUARKUS_DATASOURCE_JDBC_INITIAL_SIZE=7'
      - 'QUARKUS_DATASOURCE_JDBC_MIN_SIZE=7'
      - 'QUARKUS_DATASOURCE_JDBC_MAX_SIZE=7'
      - 'QUARKUS_DATASOURCE_JDBC_DETECT_STATEMENT_LEAKS=false'
      - 'QUARKUS_DATASOURCE_JDBC_ACQUISITION_TIMEOUT=10S'
      - 'QUARKUS_DATASOURCE_JDBC_URL=jdbc:mariadb://database:3306/rinha'
      - 'QUARKUS_DATASOURCE_USERNAME=root'
      - 'QUARKUS_DATASOURCE_PASSWORD=root'
      - 'TZ=America/Sao_Paulo'
      - 'QUARKUS_HTTP_PORT=8081'
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "90MB"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - default
    ulimits:
      nofile:
        soft: 98304
        hard: 98304

#  nginx:
#    container_name: nginx
#    image: nginx:latest
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#    ports:
#      - 9999:9999
#    depends_on:
#      - app1
#      - app2
#    deploy:
#      resources:
#        limits:
#          cpus: "0.15"
#          memory: "70MB"
#    networks:
#      - default

  envoy:
    image: envoyproxy/envoy-alpine:v1.21-latest
    container_name: envoy
    environment:
      - 'TZ=America/Sao_Paulo'
    volumes:
      -  ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "9999:9999"
    networks:
      - default
    depends_on:
      - app1
      - app2
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "90MB"
    ulimits:
      nofile:
        soft: 98304
        hard: 98304

networks:
  default:
    driver: bridge