services:
  database:
    image: mariadb:latest
    container_name: database
    mem_swappiness: 0
    security_opt:
      - seccomp:unconfined
    environment:
      - 'MARIADB_ROOT_PASSWORD=root'
      - 'MARIADB_DATABASE=rinha'
      - 'TZ=America/Sao_Paulo'
      - 'MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true'
      - 'MARIADB_MYSQL_LOCALHOST_USER: 1'
      - 'MARIADB_MYSQL_LOCALHOST_GRANTS: USAGE'
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "150MB"
    volumes:
      - ./sql/mysql-init-script.sql:/docker-entrypoint-initdb.d/mysql-init-script.sql
      - ./mysql.conf:/etc/mysql/conf.d/config-file.cnf
    networks:
      - default
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      interval: 5s
      timeout: 5s
      retries: 10
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
      core:
        soft: -1
        hard: -1
    ports:
      - 3306:3306

  app1: &api
    container_name: app1
    image: quarkus/rinha-backend-2024
    environment:
      - 'QUARKUS_LOG_LEVEL=WARN'
      - 'QUARKUS_LOG_FILE_ENABLE=false'
      - 'QUARKUS_DATASOURCE_JDBC_INITIAL_SIZE=7'
      - 'QUARKUS_DATASOURCE_JDBC_MIN_SIZE=7'
      - 'QUARKUS_DATASOURCE_JDBC_MAX_SIZE=7'
      - 'QUARKUS_DATASOURCE_JDBC_DETECT_STATEMENT_LEAKS=false'
      - 'QUARKUS_DATASOURCE_JDBC_ACQUISITION_TIMEOUT=10S'
      - 'QUARKUS_DATASOURCE_JDBC_URL=jdbc:mariadb://database:3306/rinha?cachePrepStmts=true&useServerPrepStmts=false&prepStmtCacheSize=500&prepStmtCacheSqlLimit=1024'
      - 'QUARKUS_DATASOURCE_USERNAME=root'
      - 'QUARKUS_DATASOURCE_PASSWORD=root'
      - 'TZ=America/Sao_Paulo'
      - 'QUARKUS_HTTP_PORT=8080'
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "170MB"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - default
    ulimits:
      nofile:
        soft: 98304
        hard: 98304

  app2:
    <<: *api
    container_name: app2
    environment:
      - 'QUARKUS_LOG_LEVEL=WARN'
      - 'QUARKUS_LOG_FILE_ENABLE=false'
      - 'QUARKUS_DATASOURCE_JDBC_INITIAL_SIZE=7'
      - 'QUARKUS_DATASOURCE_JDBC_MIN_SIZE=7'
      - 'QUARKUS_DATASOURCE_JDBC_MAX_SIZE=7'
      - 'QUARKUS_DATASOURCE_JDBC_DETECT_STATEMENT_LEAKS=false'
      - 'QUARKUS_DATASOURCE_JDBC_ACQUISITION_TIMEOUT=10S'
      - 'QUARKUS_DATASOURCE_JDBC_URL=jdbc:mariadb://database:3306/rinha?cachePrepStmts=true&useServerPrepStmts=false&prepStmtCacheSize=500&prepStmtCacheSqlLimit=1024'
      - 'QUARKUS_DATASOURCE_USERNAME=root'
      - 'QUARKUS_DATASOURCE_PASSWORD=root'
      - 'TZ=America/Sao_Paulo'
      - 'QUARKUS_HTTP_PORT=8081'

  haproxy:
    container_name: haproxy
    image: haproxy:latest
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    environment:
      - 'TZ=America/Sao_Paulo'
      - 'USETHREAD=1'
    ports:
      - 9999:9999
    depends_on:
      - app1
      - app2
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "60MB"
    ulimits:
      nofile:
        soft: 100000
        hard: 100000
    networks:
      - default

#  nginx:
#    container_name: nginx
#    image: nginx:stable-bullseye
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#    environment:
#      - 'TZ=America/Sao_Paulo'
#    ports:
#      - 9999:9999
#    depends_on:
#      - app1
#      - app2
#    deploy:
#      resources:
#        limits:
#          cpus: "0.15"
#          memory: "90MB"
#    ulimits:
#      nofile:
#        soft: 100000
#        hard: 100000
#    network_mode: host

#  envoy:
#    image: envoyproxy/envoy-alpine:v1.21-latest
#    container_name: envoy
#    environment:
#      - 'TZ=America/Sao_Paulo'
#    volumes:
#      -  ./envoy.yaml:/etc/envoy/envoy.yaml
#    ports:
#      - "9999:9999"
#    network_mode: host
#    depends_on:
#      - app1
#      - app2
#    deploy:
#      resources:
#        limits:
#          cpus: "0.15"
#          memory: "90MB"
#    ulimits:
#      nofile:
#        soft: 98304
#        hard: 98304

networks:
  default:
    enable_ipv6: false
    driver: bridge