quarkus:
  log:
    level: WARN
  http:
    port: 9999
    tcp-quick-ack: true
    tcp-cork: true
    tcp-fast-open: true
    http2: false
    http2-push-enabled: false
  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    jdbc:
      url: "jdbc:postgresql://localhost:5432/rinha"
      max-size: 10
      transactions: disabled