quarkus:
  log:
    level: WARN
  http:
    port: 8080
  datasource:
    db-kind: mariadb
    username: root
    password: root
    jdbc:
      url: "jdbc:mariadb://localhost:3306/rinha"
      max-size: 10
      transactions: disabled