quarkus:
  log:
    level: WARN
  http:
    port: 8080
    tcp-quick-ack: true
    tcp-cork: true
    tcp-fast-open: true
    http2: false
    http2-push-enabled: false
  datasource:
    db-kind: mariadb
    username: root
    password: root
    jdbc:
      url: "jdbc:mariadb://localhost:3306/rinha"
      max-size: 10
      transactions: disabled